;; Mtoken - SIP-010 Fungible Token
;; Generated by StacksAgent MCP

;; SIP-010 Trait Implementation
;; Note: Trait addresses are network-specific:
;; - Mainnet: SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait
;; - Testnet: ST339A455EK9PAY9NP81WHK73T1JMFC3NN0321T18.sip-010-trait-ft-standard.sip-010-trait
(impl-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait)

;; Constants
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-token-owner (err u101))
(define-constant err-insufficient-balance (err u102))

;; Token definitions
(define-fungible-token MTK u1000000)

;; Initialize token supply to contract owner
(begin
  (try! (ft-mint? MTK u1000000 contract-owner))
)

;; SIP-010 Functions

(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (begin
    (asserts! (is-eq tx-sender sender) err-not-token-owner)
    (asserts! (> amount u0) (err u103))
    (try! (ft-transfer? MTK amount sender recipient))
    (match memo to-print (print to-print) 0x)
    (ok true)))

(define-read-only (get-name)
  (ok "Mtoken"))

(define-read-only (get-symbol)
  (ok "MTK"))

(define-read-only (get-decimals)
  (ok u6))

(define-read-only (get-balance (who principal))
  (ok (ft-get-balance MTK who)))

(define-read-only (get-total-supply)
  (ok (ft-get-supply MTK)))

(define-read-only (get-token-uri)
  (ok none))
