;; My NFT - SIP-009 Non-Fungible Token
;; Generated by StacksAgent MCP

(impl-trait 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait.nft-trait)

;; Constants
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-token-owner (err u101))
(define-constant err-token-exists (err u102))
(define-constant err-token-not-found (err u103))

;; NFT definition
(define-non-fungible-token MNFT uint)

;; Data variables
(define-data-var last-token-id uint u0)
(define-data-var token-uri (string-utf8 256) u"https://example.com/nft/")

;; Data maps
(define-map token-metadata uint {uri: (string-utf8 256)})

;; SIP-009 Functions

(define-public (transfer (token-id uint) (sender principal) (recipient principal))
  (begin
    (asserts! (is-eq tx-sender sender) err-not-token-owner)
    (nft-transfer? MNFT token-id sender recipient)))

(define-read-only (get-last-token-id)
  (ok (var-get last-token-id)))

(define-read-only (get-token-uri (token-id uint))
  (ok (some (var-get token-uri))))

(define-read-only (get-owner (token-id uint))
  (ok (nft-get-owner? MNFT token-id)))

;; Mint function
(define-public (mint (recipient principal))
  (let
    (
      (token-id (+ (var-get last-token-id) u1))
    )
    (asserts! (is-eq tx-sender contract-owner) err-owner-only)
    (try! (nft-mint? MNFT token-id recipient))
    (var-set last-token-id token-id)
    (ok token-id)))

;; Set token URI
(define-public (set-token-uri (new-uri (string-utf8 256)))
  (begin
    (asserts! (is-eq tx-sender contract-owner) err-owner-only)
    (ok (var-set token-uri new-uri))))
