;; Simple Vault Contract
;; Generated by StacksAgent MCP

;; Constants
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-insufficient-balance (err u101))
(define-constant err-invalid-amount (err u102))

;; Data maps
(define-map vault-balances principal uint)

;; Data variables
(define-data-var total-deposited uint u0)

;; Public functions

(define-public (deposit (amount uint))
  (begin
    (asserts! (> amount u0) err-invalid-amount)
    (try! (stx-transfer? amount tx-sender (as-contract tx-sender)))
    (map-set vault-balances tx-sender
      (+ (default-to u0 (map-get? vault-balances tx-sender)) amount))
    (var-set total-deposited (+ (var-get total-deposited) amount))
    (ok true)))

(define-public (withdraw (amount uint))
  (let
    (
      (balance (default-to u0 (map-get? vault-balances tx-sender)))
    )
    (asserts! (> amount u0) err-invalid-amount)
    (asserts! (>= balance amount) err-insufficient-balance)
    (try! (as-contract (stx-transfer? amount tx-sender tx-sender)))
    (map-set vault-balances tx-sender (- balance amount))
    (var-set total-deposited (- (var-get total-deposited) amount))
    (ok true)))

;; Read-only functions

(define-read-only (get-balance (user principal))
  (ok (default-to u0 (map-get? vault-balances user))))

(define-read-only (get-total-deposited)
  (ok (var-get total-deposited)))
