;; TestCoin with symbol TST - SIP-010 Fungible Token
;; Generated by StacksAgent MCP

(impl-trait 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard.sip-010-trait)

;; Constants
(define-constant contract-owner tx-sender)
(define-constant err-owner-only (err u100))
(define-constant err-not-token-owner (err u101))
(define-constant err-insufficient-balance (err u102))

;; Token definitions
(define-fungible-token TST u1000000)

;; Initialize token supply to contract owner
(begin
  (try! (ft-mint? TST u1000000 contract-owner))
)

;; SIP-010 Functions

(define-public (transfer (amount uint) (sender principal) (recipient principal) (memo (optional (buff 34))))
  (begin
    (asserts! (is-eq tx-sender sender) err-not-token-owner)
    (asserts! (> amount u0) (err u103))
    (try! (ft-transfer? TST amount sender recipient))
    (match memo to-print (print to-print) 0x)
    (ok true)))

(define-read-only (get-name)
  (ok "TestCoin with symbol TST"))

(define-read-only (get-symbol)
  (ok "TST"))

(define-read-only (get-decimals)
  (ok u6))

(define-read-only (get-balance (who principal))
  (ok (ft-get-balance TST who)))

(define-read-only (get-total-supply)
  (ok (ft-get-supply TST)))

(define-read-only (get-token-uri)
  (ok none))
